// <auto-generated />
using System;
using InfinityCodexWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InfinityCodexWebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260413050413_AddCatalogHierarchyAndItemStats")]
    partial class AddCatalogHierarchyAndItemStats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("InfinityCodexWebApp.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PortraitUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "Name")
                        .IsUnique();

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("InfinityCodexWebApp.CharacterItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId", "ItemId")
                        .IsUnique();

                    b.ToTable("CharacterItems");
                });

            modelBuilder.Entity("InfinityCodexWebApp.CharacterItemNeed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId", "ItemId")
                        .IsUnique();

                    b.ToTable("CharacterItemNeeds");
                });

            modelBuilder.Entity("InfinityCodexWebApp.CharacterJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId", "JobCode")
                        .IsUnique();

                    b.ToTable("CharacterJobs");
                });

            modelBuilder.Entity("InfinityCodexWebApp.CharacterJobLevel", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobCode")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterId", "JobCode");

                    b.ToTable("CharacterJobLevels");
                });

            modelBuilder.Entity("InfinityCodexWebApp.CharacterMissionProgress", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BastokMission")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChainsOfPromathiaMission")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("EpilogueMission")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("RiseOfTheZilartMission")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SanDOriaMission")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WindurstMission")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId");

                    b.ToTable("CharacterMissionProgresses");
                });

            modelBuilder.Entity("InfinityCodexWebApp.ContentGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Tag")
                        .IsUnique();

                    b.ToTable("ContentGroups");
                });

            modelBuilder.Entity("InfinityCodexWebApp.ContentSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContentGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentGroupId", "Tag");

                    b.ToTable("ContentSources");
                });

            modelBuilder.Entity("InfinityCodexWebApp.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EquipSlotGroup")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsExclusive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRare")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawEffectText")
                        .HasColumnType("TEXT");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slot")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("InfinityCodexWebApp.ItemAccessoryStats", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Charges")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RecastSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId");

                    b.ToTable("ItemAccessoryStats");
                });

            modelBuilder.Entity("InfinityCodexWebApp.ItemAllowedJob", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobCode")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId", "JobCode");

                    b.ToTable("ItemAllowedJobs");
                });

            modelBuilder.Entity("InfinityCodexWebApp.ItemArmorStats", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Defense")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MagicDefense")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId");

                    b.ToTable("ItemArmorStats");
                });

            modelBuilder.Entity("InfinityCodexWebApp.ItemSource", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContentSourceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId", "ContentSourceId");

                    b.ToTable("ItemSources");
                });

            modelBuilder.Entity("InfinityCodexWebApp.ItemStatModifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StatValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId", "SortOrder");

                    b.HasIndex("ItemId", "StatKey");

                    b.ToTable("ItemStatModifiers");
                });

            modelBuilder.Entity("InfinityCodexWebApp.ItemWeaponStats", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Damage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Delay")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Dps")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.ToTable("ItemWeaponStats");
                });

            modelBuilder.Entity("InfinityCodexWebApp.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscordId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRegistrationComplete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreferredJobsCsv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RegistrationCompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiscordId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InfinityCodexWebApp.UserPreferredJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "JobCode")
                        .IsUnique();

                    b.ToTable("UserPreferredJobs");
                });

            modelBuilder.Entity("InfinityCodexWebApp.ContentSource", b =>
                {
                    b.HasOne("InfinityCodexWebApp.ContentGroup", null)
                        .WithMany()
                        .HasForeignKey("ContentGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("InfinityCodexWebApp.ItemAccessoryStats", b =>
                {
                    b.HasOne("InfinityCodexWebApp.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfinityCodexWebApp.ItemArmorStats", b =>
                {
                    b.HasOne("InfinityCodexWebApp.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfinityCodexWebApp.ItemStatModifier", b =>
                {
                    b.HasOne("InfinityCodexWebApp.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfinityCodexWebApp.ItemWeaponStats", b =>
                {
                    b.HasOne("InfinityCodexWebApp.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
